import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FaGithub } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="bg-mobileSvg bg-fixed bg-cover bg-center h-screen text-white"
      >
        <nav className="w-screen bg-navbar grid justify-items-center p-5 text-3xl border-2 border-white rounded-xl">
          
          <Link href="/" className="pb-4">
          <p className="relative group">
            <span>Home</span>
            <span className="absolute -bottom-1 left-1/2 w-0 h-1 bg-white group-hover:w-1/2 group-hover:transition-all rounded-r-lg"></span>
            <span className="absolute -bottom-1 right-1/2 w-0 h-1 bg-white group-hover:w-1/2 group-hover:transition-all rounded-l-lg"></span>
          </p>
          </Link>
          <Link href="/resume" className="pb-4">
          <p className="relative group">
            <span>Resume</span>
            <span className="absolute -bottom-1 left-1/2 w-0 h-1 bg-white group-hover:w-1/2 group-hover:transition-all rounded-r-lg"></span>
            <span className="absolute -bottom-1 right-1/2 w-0 h-1 bg-white group-hover:w-1/2 group-hover:transition-all rounded-l-lg"></span>
          </p>
          </Link>
          <Link href="/work">
          <p className="relative group">
            <span>My Work</span>
            <span className="absolute -bottom-1 left-1/2 w-0 h-1 bg-white group-hover:w-1/2 group-hover:transition-all rounded-r-lg"></span>
            <span className="absolute -bottom-1 right-1/2 w-0 h-1 bg-white group-hover:w-1/2 group-hover:transition-all rounded-l-lg"></span>
          </p>
          </Link>
        </nav>
        
        {children}

        <footer className="w-full text-center bg-navbar p-5 mt-5 text-xl border-2 border-white rounded-xl">
          <h3 className="font-bold">Contact Me</h3>
          <p className="py-4">Email: desqui048@west-mec.org</p>
          <div className="flex justify-center items-center pb-4">
            <Link href={"https://github.com/Diego-Esquivias"} target="_blank">
              <FaGithub className="mr-3" size={25} />
            </Link>
            <p>Github: Diego Esquivias</p>
          </div>
          <p>&copy; 2024 My Portfolio</p>
        </footer>
      </body>
    </html>
  );
}
